language: python

matrix:
  include:
    - { python: 2.7, env: TOXENV=py27-dj18 }
    - { python: 3.4, env: TOXENV=py34-dj18 }
    - { python: 2.7, env: TOXENV=py27-dj19 }
    - { python: 3.4, env: TOXENV=py34-dj19 }
    - { python: 2.7, env: TOXENV=py27-dj110 }
    - { python: 3.4, env: TOXENV=py34-dj110 }
    - { python: 2.7, env: TOXENV=py27-dj111 }
    - { python: 3.6, env: TOXENV=py36-dj111 }
    - python: 3.6
      env: TOXENV=py36-dj20 DATABASE_URL='postgres://postgres@127.0.0.1/generic_plus'
  allow_failures:
    - env: TOXENV=py36-dj20 DATABASE_URL='postgres://postgres@127.0.0.1/generic_plus'

sudo: false

cache:
  pip: true

before_script:
  - if [ "${DATABASE_URL%%:*}" == "postgres" ]; then psql -c "DROP DATABASE IF EXISTS ${DATABASE_URL##*/};" -U postgres; fi
  - if [ "${DATABASE_URL%%:*}" == "postgres" ]; then psql -c "create database ${DATABASE_URL##*/};" -U postgres; fi

install:
    - pip install tox

script:
    - tox
