language: python

matrix:
  include:
    - { python: 2.7, env: TOXENV=py27-dj111 }
    - { python: 3.7, env: TOXENV=py37-dj111 }
    - { python: 3.7, env: TOXENV=py37-dj20 }
    - { python: 3.7, env: TOXENV=py37-dj21 }
    - { python: 3.7, env: TOXENV=py37-dj22 }
    - { python: 3.7, env: TOXENV=py37-dj30 }

sudo: false

cache:
  pip: true

install:
    - pip install tox

script:
    - tox
