language: python

matrix:
  include:
    - { python: 2.7, env: TOXENV=py27-dj18 }
    - { python: 3.4, env: TOXENV=py34-dj18 }
    - { python: 2.7, env: TOXENV=py27-dj111 }
    - { python: 3.6, env: TOXENV=py36-dj111 }
    - { python: 3.6, env: TOXENV=py36-dj20 }
    - { python: 3.6, env: TOXENV=py36-dj21 }
  allow_failures:
    - env: TOXENV=py36-dj21

sudo: false

cache:
  pip: true

install:
    - pip install tox

script:
    - tox
